springdoc:
  swagger-ui:
    path: /ui
  api-docs:
    path: /api-docs
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vehicles
    username: vehicles
    password: vehicles
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate   # schema managed by Flyway
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org.hibernate.SQL: warn